name: scraper-san-juan-gobierno

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # install the python version needed

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          apt-get install python-fontforge

      - name: Nerdfonts
        run: |
          git clone https://github.com/ryanoasis/nerd-fonts
          apt-get install fontforge
          cd fonts && python ../scripts/nerdfonts.py
