name: scraper-san-juan-gobierno

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # install the python version needed

      - name: Install requirements
        run: |

          sudo apt-get install software-properties-common
          sudo apt-get update
          sudo apt-get install fontforge python3-fontforge python-configparser tree

      - name: Patching
        run: |

          git clone https://github.com/ToxicFrog/Ligaturizer
          git clone https://github.com/bexter989/nerdfont-patcher.git && cp -rf nerdfont-patcher/* ./fonts/ && cd fonts
          python ../scripts/nerdfonts.py && cd ../Ligaturizer
          python ../scripts/copier.py
          tree .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./fonts/Patched
