name: scraper-san-juan-gobierno

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # install the python version needed

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          sudo apt update
          sudo apt-get install python3-fontforge wget

      - name: Cache
        id: caching
        uses: actions/cache@v2
        env:
          cache-name: cacher
        with:
          path: ./nerd-fonts-master
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Download nerdfonts
        if: steps.myCacheStep.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/ryanoasis/nerd-fonts/archive/refs/heads/master.zip
          unzip master.zip

      - name: Nerdfonts
        run: |
          cd fonts && python ../scripts/nerdfonts.py
